[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 200
evm_version = 'cancun'

remappings = [
    '@account-abstraction=lib/account-abstraction/contracts/',
    '@openzeppelin=../v0_7/lib/openzeppelin-contracts/',
]

allow_paths = ["../v0_7/lib"]