[package]
name = "alchemy-bundler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive", "env"] }
ethers = { version = "1.0.2", features = ["ws"] }
jsonrpsee = { version = "0.16.2", features = ["macros", "server"] }
prost = "0.11.6"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "signal"] }
tonic = "0.8.3"
tonic-reflection = "0.6.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-appender = "0.2.2"
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
metrics-util = "0.14.0"
parking_lot = "0.12.1"
dotenv = "0.15.0"

[build-dependencies]
ethers = "1.0.2"
tonic-build = "0.8.4"
