[package]
name = "alchemy-bundler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
ethers = "1.0.2"
jsonrpsee = { version = "0.16.2", features = ["macros", "server"] }
primitive-types = "0.12.1"
prost = "0.11.6"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.3"
tonic-reflection = "0.6.0"
tracing = "0.1.37"

[build-dependencies]
tonic-build = "0.8.4"
