[workspace]
members = [
    "bin/*",
    "crates/*",
]
default-members = ["bin/rundler"]
resolver = "2"

[workspace.package]
version = "0.1.0-rc0"
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alchemyplatform/rundler"

[workspace.dependencies]
anyhow = "1.0.70"
async-trait = "0.1.73"
cargo-husky = { version = "1", default-features = false, features = ["user-hooks"] }
ethers = "2.0.10"
futures = "0.3.28"
futures-util = "0.3.28"
itertools = "0.12.1"
jsonrpsee = "0.20.1"
metrics = "0.22.1"
mockall = "0.12.1"
parse-display = "0.9.0"
pin-project = "1.0.12"
prost = "0.12.0"
serde = "1.0.160"
serde_json = "1.0.64"
rand = "0.8.5"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls"] }
rustls = "0.22.2"
thiserror = "1.0.40"
tokio = { version = "1.27.0", default-features = false }
tokio-util = "0.7.8"
tonic = "0.11.0"
tonic-build = "0.11.0"
tonic-health = "0.11.0"
tonic-reflection = "0.11.0"
tonic-types = "0.11.0"
tower = "0.4.13"
tracing = "0.1.37"
strum = { version = "0.26.1", features = ["derive"] }
url = "2.3.1"
