[workspace]
members = [
    "bin/rundler",
    "bin/tools",
    "crates/rundler",
    "crates/pool",
    "crates/provider",
    "crates/sim",
    "crates/task",
    "crates/types",
    "crates/utils"
]
default-members = ["bin/rundler"]

[workspace.package]
version = "0.1.0-beta"
edition = "2021"
rust-version = "1.71"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alchemyplatform/rundler"

[workspace.dependencies]
anyhow = "1.0.70"
async-trait = "0.1.73"
cargo-husky = { version = "1", default-features = false, features = ["user-hooks" ] }
ethers = "2.0.8"
futures = "0.3.28"
futures-util = "0.3.28"
metrics = "0.21.0"
mockall = "0.11.4"
parse-display = "0.8.0"
pin-project = "1.0.12"
prost = "0.12.0"
serde = "1.0.160"
serde_json = "1.0.64"
rand = "0.8.5"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls"] }
thiserror = "1.0.40"
tokio = { version = "1.27.0", default-features = false }
tokio-util = "0.7.8"
tonic = "0.10.0"
tonic-build = "0.10.0"
tonic-health = "0.10.0"
tonic-reflection = "0.10.0"
tonic-types = "0.10.0"
tower = "0.4.13"
tracing = "0.1.37"
strum = "0.25.0"
url = "2.3.1"
