[workspace]
members = [
    "bin/*",
    "crates/*",
]
default-members = ["bin/rundler"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
rust-version = "1.80"
license = "LGPL-3.0-only"
repository = "https://github.com/alchemyplatform/rundler"

[workspace.dependencies]
anyhow = "1.0.86"
alloy-contract = "0.2.1"
alloy-primitives = "0.7.7"
alloy-sol-macro = "0.7.7"
alloy-sol-types =  "0.7.7"
async-trait = "0.1.81"
cargo-husky = { version = "1", default-features = false, features = ["user-hooks"] }
ethers = "2.0.14"
futures = "0.3.30"
futures-util = "0.3.30"
itertools = "0.13.0"
jsonrpsee = "0.24.3"
metrics = "0.23.0"
mockall = "0.13.0"
parse-display = "0.10.0"
pin-project = "1.1.5"
prost = "0.13.1"
serde = "1.0.209"
serde_json = "1.0.127"
rand = "0.8.5"
reqwest = { version = "0.11.27", default-features = false, features = ["rustls-tls"] }
rustls = "0.23.12"
thiserror = "1.0.63"
tokio = { version = "1.39.3", default-features = false }
tokio-util = "0.7.11"
tonic = "0.12.2"
tonic-build = "0.12.2"
tonic-health = "0.12.2"
tonic-reflection = "0.12.2"
tonic-types = "0.12.2"
tower = { version = "0.4.13", features = ["timeout"] }
tracing = "0.1.40"
strum = { version = "0.26.3", features = ["derive"] }
url = "2.5.2"
