[build]
pre-build = [
    "apt-get update && apt-get install --assume-yes --no-install-recommends libclang-5.0-dev clang-5.0 ca-certificates",
    "update-ca-certificates"
]
dockerfile = "./Dockerfile.build"
