# configuration file for cargo-sort.
always_trailing_comma = false
multiline_trailing_comma = true
space_around_eq = true
compact_arrays = false
compact_inline_tables = false
trailing_newline = true
key_value_newlines = true
allowed_blank_lines = 1
