[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 200
evm_version = 'paris'
allow_internal_expect_revert = true

remappings = [
    'forge-std/=lib/forge-std/src',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    '@openzeppelin=../v0_7/lib/openzeppelin-contracts/',
    'common=src/'
]
