name = "Ethereum"
id = 1

flashbots_enabled = true
flashbots_relay_url = "https://relay.flashbots.net"

max_transaction_size_bytes = 131072

min_max_priority_fee_per_gas = 50000000
block_gas_limit = 36000000
eip7702_enabled = true
eip7623_enabled = true
